### ISSUE TITLE
pgadmin III 客户端表DDL问题

### ISSUE THREAD

**Issue by rangez** [water32/gpmagic4share#1]
服务器端使用   pg_gump -s -t rle：
CREATE TABLE public.rle (
    a integer ENCODING (compresslevel=3,compresstype=rle_type,blocksize=32768),
    b character(50) ENCODING (compresslevel=3,compresstype=rle_type,blocksize=32768),
    c timestamp without time zone ENCODING (compresslevel=3,compresstype=rle_type,blocksize=32768),
    d text ENCODING (compresslevel=3,compresstype=rle_type,blocksize=32768)
)
WITH (appendonly='true', compresslevel='3', orientation='column', compresstype=`rle_type`)
 DISTRIBUTED BY (a);

pgadmin III客户端显示：
CREATE TABLE rle
(
  a integer,
  b character(50),
  c timestamp without time zone,
  d text
)
WITH (APPENDONLY=true, COMPRESSLEVEL=3, ORIENTATION=column, COMPRESSTYPE=`rle`, BLOCKSIZE=32768, 
  OIDS=FALSE
)
DISTRIBUTED BY (a);

**Comment by water32** [comment]
显示不全的问题已经修复了，可以正确的显示rle_type，不过，字段上不显示的问题，难以修复，也不打算修复，因为字段上定义不同的压缩算法是几乎没有意义的

**Comment by water32** [comment]
可以正确的显示rle_type

**Comment by water32** [comment]
显示不全的问题已经修复了，可以正确的显示rle_type，不过，字段上不显示的问题，难以修复，也不打算修复，因为字段上定义不同的压缩算法是几乎没有意义的
